name: service-hello-world

cloud: eks-ray-cloud

compute_config:
  head_node:
    required_resources:
      CPU: 2
      memory: 8Gi

runtime_env:
  pip:
    - fastapi
    - uvicorn

working_dir: .

applications:
  - import_path: main:app_deploy
